### ISSUE TITLE
Automatically convert files not named "index" for pretty URLs

### ISSUE THREAD

**Issue by adamwathan** [adamwathan/jigsaw#2]
If I have a file named `about-us.blade.php`, create an `about-us` folder and stick the file inside as `index.html`.

**Comment by adamwathan** [comment]
Done

**Comment by dreamxcape** [comment]
When the build is generated, the header css files still have the standard path and are not appended with a ../. Is this the default behaviour? How do I call in the css files in second-levels of the site?
